"""sprint 9-10: stock multi-ubicacion y presupuestos

Revision ID: 030c8e2c167e
Revises: 9e8a83189515
Create Date: 2026-05-13 20:19:58.691136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030c8e2c167e'
down_revision: Union[str, None] = '9e8a83189515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_tipo', sa.Enum('deposito_propio', 'en_obra', 'comprado_no_retirado', name='ubicacionstocktipo'), nullable=False),
    sa.Column('ubicacion_ref', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_material_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_material_ubicacion_tipo'), ['ubicacion_tipo'], unique=False)

    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'aprobado', 'cerrado', name='estadopresupuesto'), nullable=False),
    sa.Column('total_estimado', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('aprobado_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_obra_id'), ['obra_id'], unique=False)

    op.create_table('presupuesto_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario_estimado', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Data migration: seed StockMaterial(deposito_propio) con el stock actual de cada Material.
    # El campo Material.stock se mantiene como cache para no romper queries existentes.
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO stock_material (material_id, ubicacion_tipo, ubicacion_ref, cantidad, updated_at)
        SELECT id, 'deposito_propio', NULL, COALESCE(stock, 0), CURRENT_TIMESTAMP
        FROM materiales
        WHERE COALESCE(stock, 0) > 0
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presupuesto_items')
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_obra_id'))

    op.drop_table('presupuestos')
    with op.batch_alter_table('stock_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_material_ubicacion_tipo'))
        batch_op.drop_index(batch_op.f('ix_stock_material_material_id'))

    op.drop_table('stock_material')
    # ### end Alembic commands ###
