"""sprint 11 - telegram bot fields on user

Revision ID: 6706465fbb3c
Revises: 030c8e2c167e
Create Date: 2026-05-17 18:05:58.676328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6706465fbb3c'
down_revision: Union[str, None] = '030c8e2c167e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram_username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram_vinculacion_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram_vinculacion_exp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id'), ['telegram_chat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id'))
        batch_op.drop_column('telegram_vinculacion_exp')
        batch_op.drop_column('telegram_vinculacion_code')
        batch_op.drop_column('telegram_username')
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
