"""initial schema (sprint 0..7)

Revision ID: 9e8a83189515
Revises: 
Create Date: 2026-05-11 17:42:52.188035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8a83189515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cuit', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('rubro', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('plazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('moroso', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regimenes_fiscales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('iva_default', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('aplica_iibb', sa.Boolean(), nullable=True),
    sa.Column('aplica_ganancias', sa.Boolean(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin_finanzas', 'admin', 'supervisor', 'usuario_bot', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'rejected', name='userstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agent_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('regimen_fiscal_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regimen_fiscal_id'], ['regimenes_fiscales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cuit'), ['cuit'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_nombre'), ['nombre'], unique=False)

    op.create_table('cuadrillas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('cantidad_miembros', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('experiencia', sa.Integer(), nullable=True),
    sa.Column('eficiencia', sa.Float(), nullable=True),
    sa.Column('capataz_id', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capataz_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('icono', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiales_categoria'), ['categoria'], unique=False)

    op.create_table('socios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=True),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('participacion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('socios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_socios_cuit'), ['cuit'], unique=False)

    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_input_json', sa.Text(), nullable=True),
    sa.Column('tool_output_json', sa.Text(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('canal', sa.Enum('whatsapp', 'web', 'automatico', 'agente_ia', name='canalcarga'), nullable=True),
    sa.Column('status', sa.Enum('executed', 'pending', 'confirmed', 'cancelled', name='agentactionstatus'), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_tool_name'), ['tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_user_id'), ['user_id'], unique=False)

    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('regimen_fiscal_id', sa.Integer(), nullable=True),
    sa.Column('tipo_facturacion', sa.Enum('TOTAL_BLANCO', 'TOTAL_NEGRO', 'MIXTA', 'SIN_DEFINIR', name='tipofacturacion'), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto_contrato', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('EN_CURSO', 'PAUSADA', 'FINALIZADA', 'CANCELADA', 'planificacion', name='obrastatus'), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icono', sa.String(length=20), nullable=True),
    sa.Column('salud', sa.Enum('optimo', 'atencion', 'critico', name='obrasalud'), nullable=True),
    sa.Column('progreso', sa.Float(), nullable=True),
    sa.Column('superficie_m2', sa.Float(), nullable=True),
    sa.Column('pisos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['regimen_fiscal_id'], ['regimenes_fiscales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.Enum('FC_A', 'FC_B', 'FC_C', 'NC_A', 'NC_B', 'ND_A', 'ND_B', 'RECIBO_X', 'REMITO', name='tipocomprobante'), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=True),
    sa.Column('nro_comprobante', sa.String(length=20), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('cuit_emisor', sa.String(length=13), nullable=False),
    sa.Column('cuit_receptor', sa.String(length=13), nullable=False),
    sa.Column('neto_gravado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('neto_no_gravado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('iva_21', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('iva_105', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cae', sa.String(length=20), nullable=True),
    sa.Column('cae_vencimiento', sa.Date(), nullable=True),
    sa.Column('es_venta', sa.Boolean(), nullable=False),
    sa.Column('estado_fiscal', sa.Enum('VALIDO', 'SIN_CAE', 'VENCIDO', 'ANULADO', name='estadofiscal'), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etapas_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nro_etapa', sa.Integer(), nullable=False),
    sa.Column('monto_contractual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('porcentaje_avance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_EJECUCION', 'EJECUTADA', 'FACTURADA', 'COBRADA', name='etapaestado'), nullable=False),
    sa.Column('fecha_estimada', sa.Date(), nullable=True),
    sa.Column('fecha_cobro_real', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('icono', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_progreso', 'bloqueado', 'completado', name='frenteestado'), nullable=True),
    sa.Column('progreso', sa.Float(), nullable=True),
    sa.Column('cuadrilla_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['cuadrillas.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('destinatario', sa.String(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('log_only', 'pending', 'sent', 'failed', name='outboundmessagestatus'), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('context_key', sa.String(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_action_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['related_action_id'], ['agent_actions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_messages_context_key'), ['context_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_destinatario'), ['destinatario'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_status'), ['status'], unique=False)

    op.create_table('aportes_socios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('etapa_reintegro_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aporte', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('medio_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE_PROPIO', 'CHEQUE_TERCERO', 'DEPOSITO_BANCARIO', name='mediopago'), nullable=False),
    sa.Column('estado_devolucion', sa.Enum('PENDIENTE', 'DEVUELTO_PARCIAL', 'DEVUELTO_TOTAL', name='estadodevolucion'), nullable=False),
    sa.Column('monto_devuelto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etapa_reintegro_id'], ['etapas_obra.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('frente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('avance', 'material_llegada', 'incidente', 'inspeccion', 'foto', 'hito', 'otro', name='eventotipo'), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('canal', sa.Enum('whatsapp', 'web', 'automatico', 'agente_ia', name='canalcarga'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('es_critico', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frente_id'], ['frentes.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_fecha'), ['fecha'], unique=False)

    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('frente_id', sa.Integer(), nullable=True),
    sa.Column('cuadrilla_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'en_progreso', 'completada', 'bloqueada', name='taskstatus'), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('completada_at', sa.DateTime(), nullable=True),
    sa.Column('creada_por_id', sa.Integer(), nullable=True),
    sa.Column('canal_creacion', sa.Enum('whatsapp', 'web', 'automatico', 'agente_ia', name='canalcarga'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creada_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['cuadrillas.id'], ),
    sa.ForeignKeyConstraint(['frente_id'], ['frentes.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', name='tipomovimiento'), nullable=False),
    sa.Column('origen_ingreso', sa.Enum('ANTICIPO_CLIENTE', 'CERTIFICADO_ETAPA', 'PAGO_FINAL', 'AJUSTE_CONTRATO', 'APORTE_SOCIO_RCA', 'DEVOLUCION_PROVEEDOR', name='origeningreso'), nullable=True),
    sa.Column('categoria_egreso', sa.Enum('MANO_DE_OBRA', 'MATERIALES', 'SUBCONTRATO', 'SERVICIO_EXTERNO', 'GASTO_DIRECTO_OBRA', 'HERRAMIENTA_EQUIPO', 'APORTE_PRESTAMO', name='categoriaegreso'), nullable=True),
    sa.Column('concepto', sa.String(length=300), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('medio_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE_PROPIO', 'CHEQUE_TERCERO', 'DEPOSITO_BANCARIO', name='mediopago'), nullable=False),
    sa.Column('bancarizado', sa.Boolean(), nullable=False),
    sa.Column('nro_cheque', sa.String(length=30), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('fecha_vto_cheque', sa.Date(), nullable=True),
    sa.Column('tiene_comprobante', sa.Boolean(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('aporte_socio_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('CONFIRMADO', 'A_REVISAR', name='estadomovimiento'), nullable=False),
    sa.Column('hoja_fisica', sa.String(length=100), nullable=True),
    sa.Column('canal', sa.Enum('whatsapp', 'web', 'automatico', 'agente_ia', name='canalcarga'), nullable=False),
    sa.Column('cargado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aporte_socio_id'], ['aportes_socios.id'], ),
    sa.ForeignKeyConstraint(['cargado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas_obra.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_obra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_obra_etapa_id'), ['etapa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_obra_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_obra_obra_id'), ['obra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_obra_tipo'), ['tipo'], unique=False)

    op.create_table('notas_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('importante', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_obra.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retenciones_sufridas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('tipo_retencion', sa.Enum('GANANCIAS', 'IIBB', 'IVA_RETENCION', 'SUSS', name='tiporetencion'), nullable=False),
    sa.Column('alicuota', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('base_calculo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_retenido', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('nro_constancia', sa.String(length=50), nullable=True),
    sa.Column('fecha_retencion', sa.Date(), nullable=False),
    sa.Column('agente_retencion', sa.String(length=200), nullable=True),
    sa.Column('cuit_agente', sa.String(length=13), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_obra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retenciones_sufridas')
    op.drop_table('notas_obra')
    with op.batch_alter_table('movimientos_obra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_obra_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimientos_obra_obra_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_obra_fecha'))
        batch_op.drop_index(batch_op.f('ix_movimientos_obra_etapa_id'))

    op.drop_table('movimientos_obra')
    op.drop_table('ordenes_trabajo')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_fecha'))

    op.drop_table('eventos')
    op.drop_table('aportes_socios')
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_messages_status'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_notification_type'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_destinatario'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_context_key'))

    op.drop_table('outbound_messages')
    op.drop_table('movimientos_material')
    op.drop_table('frentes')
    op.drop_table('etapas_obra')
    op.drop_table('comprobantes')
    op.drop_table('obras')
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_tool_name'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_status'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_created_at'))

    op.drop_table('agent_actions')
    with op.batch_alter_table('socios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_socios_cuit'))

    op.drop_table('socios')
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiales_categoria'))

    op.drop_table('materiales')
    op.drop_table('cuadrillas')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nombre'))
        batch_op.drop_index(batch_op.f('ix_clientes_cuit'))

    op.drop_table('clientes')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_user_id'))

    op.drop_table('agent_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('regimenes_fiscales')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
